Заполнение шаблона данными
htmlacademy-javascript/1281623-keksobooking-27 pull request #6
Opened 2022-10-20 20:28 UTC by arty-violet

2022-10-20 22:19 UTC, sahaviev commented on js/data.js
> +const TYPES_OF_HOUSING = [
Массивы нужно называть как существительные во множественном числе. Т.е. **TYPES_OF_HOUSINGS**, предыдущее название тоже было нормальным.

2022-10-20 22:21 UTC, sahaviev commented on js/template.js
> +offers.forEach(({ author, offer }) => {
В целом неплохо.
Единственное я бы посоветовал обернуть это в функцию **renderOffers** и экспортировать эту функцию.
В main уже когда ты сгенерировал офферы вызывать для них отрисовку передавая ее в функцию:
```
const offers = createOffers(10);
renderOffers(offers);
```

2022-10-20 22:23 UTC, sahaviev commented on js/main.js
> +console.log(createOffers(1));
Пусть main.js станет модулем который объединяет остальные модули.
Для этого сделай то что описал выше для модуля template.js.

2022-10-20 22:23 UTC, sahaviev requested changes
Оставил комментарии и отправляю на доработку

2022-10-21 15:34 UTC, sahaviev commented on js/render-offers.js
> +const cardContainerFragment = document.createDocumentFragment();
Этот фрагмент нужно создавать внутри функции renderOffers.
Иначе при повторном вызове renderOffers у тебя предыдущие значения будут сохраняться и вставляться повторно =)

2022-10-21 15:34 UTC, merged

2022-10-21 15:51 UTC, arty-violet commented on js/render-offers.js
> +const cardContainerFragment = document.createDocumentFragment();
Принято. Спасибо. Исправлю.